FROM debian:stable-slim

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get upgrade -y

RUN apt-get install wget -y

RUN wget https://cdn.azul.com/zulu/bin/zulu15.27.17-ca-jdk15.0.0-linux_amd64.deb -O /tmp/install.deb 2>/dev/null

RUN mkdir -p /usr/share/man/man1

RUN apt-get install /tmp/install.deb -y

RUN rm /tmp/install.deb

RUN apt-get install maven -y

RUN apt-get install gcc gperf cmake ccache -y

RUN apt-get install libssl-dev liblz4-dev libgflags-dev zlib1g-dev -y

RUN apt-get install build-essential -y

RUN apt-get install python3 -y

RUN apt-get install php-cli -y

RUN apt-get install libreadline-dev git -y

#RUN ./build.sh

#ENTRYPOINT [ "/bin/bash" ]

ARG UNAME=debian
ARG UID=1000
ARG GID=1000
RUN groupadd -g $GID -o $UNAME
RUN useradd -m -u $UID -g $GID -o -s /bin/bash $UNAME
USER $UNAME

RUN mkdir /home/$UNAME/work

RUN mkdir /home/$UNAME/output

WORKDIR /home/$UNAME/work

ENV CCACHE_DIR=/home/$UNAME/.ccache

ENV JAVA_HOME=/usr/lib/jvm/zulu-15-amd64

ENV JAVA_INCLUDE_PATH=/usr/lib/jvm/zulu-15-amd64/include

ENV TRAVIS_CPU_ARCH=amd64

ENV TRAVIS_OS_NAME=linux

ENV TRAVIS_BUILD_DIR=/home/$UNAME/work

ENV TRAVIS_OUTPUT_DIR=/home/$UNAME/output

CMD ["bash"]
